backend:
  name: github
  repo: SamueleFerri/oriettareiki
  branch: main
  base_url: https://orietta-login.vercel.app

media_folder: "static/images/uploads" # Dove finiscono le foto caricate
public_folder: "/images/uploads"

# --- LINK ---
site_url: https://oriettavandi.com
display_url: https://oriettareiki.vercel.app
#logo_url: https://oriettareiki.vercel.app/images/favicon.png

locale: "it"

collections:
  # SEZIONE HOMEPAGE
  - name: "home"
    label: "Homepage"
    files:
      - name: "index"
        label: "Contenuti Homepage"
        file: "content/_index.md"
        fields:
          - {label: "Titolo Principale", name: "title", widget: "string"}
          - { label: "Meta Descrizione (Per Google)", name: "description", widget: "text" }
          - {label: "Sottotitolo / Frase Ispirazionale", name: "subtitle", widget: "text"}
          - {label: "Foto di Copertina", name: "image", widget: "image"}
          - {label: "Testo di Benvenuto", name: "body", widget: "markdown"}

  # SEZIONE TRATTAMENTI
  - name: "trattamenti"
    label: "Trattamenti"
    folder: "content/trattamenti"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome Trattamento", name: "title", widget: "string"}
      - {label: "Foto", name: "image", widget: "image"}
      - {label: "Descrizione Breve", name: "description", widget: "text"}
      - {label: "Descrizione Completa", name: "body", widget: "markdown"}
      - {label: "Prezzo (Opzionale)", name: "price", widget: "string", required: false}

# SEZIONE NEWS
  - name: "news"
    label: "News ed Eventi"
    folder: "content/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo News", name: "title", widget: "string"}
      - {label: "Data Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine Principale", name: "image", widget: "image"}
      - {label: "Descrizione Breve (Anteprima)", name: "description", widget: "text"}
      - {label: "Testo della News", name: "body", widget: "markdown"}

  # SEZIONE CHI SONO
  - name: "about"
    label: "Chi Sono"
    files:
      - name: "about"
        label: "Pagina Chi Sono"
        file: "content/about.md"
        fields:
          - {label: "Titolo", name: "title", widget: "string", default: "Chi Sono"}
          - {label: "La mia foto", name: "image", widget: "image"}
          - {label: "La mia storia", name: "body", widget: "markdown"}